In [3]:
import pandas as pd
import openpyxl

In [4]:
def make_df(year,category,month_ranges,dep):
    df=pd.DataFrame()
    
    if year=="2022":
        names_en_1=['Department',
        'ITE_DC:Total','ITE_DC:Cases','ITE_DC:Rate',
        'ITE_RDC:Total','ITE_RDC:Cases','ITE_RDC:Rate',
        'IPE_DG:Total','IPE_DG:Cases','IPE_DG:Rate',
        'IPT_DA:Total','IPT_DA:Cases','IPT_DA:Rate',
        'IPT:Total','IPT_RDA:Cases','IPT_RDA:Rate','IPT_SP:Cases','IPT_SP:Rate','IPT_O:Cases','IPT_O:Rate']
        
        names_en_2=['Department','Province','District','Ubigeous',
        'ITE_DC:Total','ITE_DC:Cases','ITE_DC:Rate',
        'ITE_RDC:Total','ITE_RDC:Cases','ITE_RDC:Rate',
        'IPE_DG:Total','IPE_DG:Cases','IPE_DG:Rate',
        'IPT_DA:Total','IPT_DA:Cases','IPT_DA:Rate',
        'IPT_RDA:Total','IPT_RDA:Cases','IPT_RDA:Rate','IPT_SP:Cases','IPT_SP:Rate','IPT_O:Cases','IPT_O:Rate']
        
        names_an_1=['Department','Total',
       'AT:Cases','AT:Rate',
       'AL:Cases','AL:Rate',
       'AM:Cases','AM:Rate',
       'AS:Cases','AS:Rate']
        
        names_an_2=['Department','Province','District','Ubigeous','Total',
       'AT:Cases','AT:Rate',
       'AL:Cases','AL:Rate',
       'AM:Cases','AM:Rate',
       'AS:Cases','AS:Rate']
        
        names_imc_clap_1=['Department',
        'IMC_PG:Total','IMC_PG_BP:Cases','IMC_PG_BP:Rate','IMC_PG_SP:Cases','IMC_PG_SP:Rate','IMC_PG_O:Cases','IMC_PG_O:Rate',
        'CLAP:Total','CLAP_DP:Cases','CLAP_DP:Rate','CLAP_SP:Cases','CLAP_SP:Rate']
        
        names_imc_clap_2=['Department','Province','District','Ubigeous',
        'IMC_PG:Total','IMC_PG_BP:Cases','IMC_PG_BP:Rate','IMC_PG_SP:Cases','IMC_PG_SP:Rate','IMC_PG_O:Cases','IMC_PG_O:Rate',
        'CLAP:Total','CLAP_DP:Cases','CLAP_DP:Rate','CLAP_SP:Cases','CLAP_SP:Rate']

        
        
        if category=="children" :
            if (("EN" in dep)and("DEP" in dep)):    
                print(f"{year}_{category}_{dep}")        
                skiprows=7
                usecols="B:U"
                names=names_en_1
                nrows=25
                skipfooter=0
            elif (("EN" in dep)and("DIRESA" in dep)):    
                print(f"{year}_{category}_{dep}")        
                skiprows=7
                usecols="B:U"
                names=names_en_1
                nrows=29
                skipfooter=0                
            elif ("EN" in dep) and ("DISTRITO" in dep):
                print(f"{year}_{category}_{dep}")        
                skiprows=7
                usecols="B:X"
                names=names_en_2
                nrows=None
                skipfooter=7                
            elif (("Anemia" in dep) and ("DEP" in dep)) :
                print(f"{year}_{category}_{dep}")        
                usecols='B:K'
                skiprows=6
                names=names_an_1
                nrows=25
                skipfooter=0
            elif (("Anemia" in dep) and ("DIRESA" in dep)) :
                print(f"{year}_{category}_{dep}")        
                usecols='B:K'
                skiprows=6
                names=names_an_1
                nrows=29
                skipfooter=0
            elif (("Anemia" in dep) and ("DISTRITO" in dep)) :
                print(f"{year}_{category}_{dep}")        
                usecols='B:N'
                skiprows=6
                names=names_an_2
                nrows=None
                skipfooter=5
                
            df=pd.read_excel(f"./data/{year}/{category}/{category}_{year}_{month_ranges}.xlsx",
                             sheet_name=dep,
                             usecols=usecols,
                             skiprows=skiprows,
                             nrows=nrows,
                             skipfooter=skipfooter,
                             engine='openpyxl',
                             header=None,
                             names=names)
            
        elif category=="foreign_children":
            
            if (("EN" in dep)and("DEP" in dep)):    
                print(f"{year}_{category}_{dep}")        
                skiprows=7
                usecols="B:U"
                names=names_en_1
                nrows=25
                skipfooter=0
            elif (("EN" in dep)and("DIRESA" in dep)):    
                print(f"{year}_{category}_{dep}")        
                skiprows=7
                usecols="B:U"
                names=names_en_1
                nrows=29
                skipfooter=0
            elif ("EN" in dep) and ("DISTRITO" in dep):
                print(f"{year}_{category}_{dep}")        
                skiprows=7
                usecols="B:X"
                names=names_en_2
                nrows=None
                skipfooter=5
            elif (("Anemia" in dep) and ("DEP" in dep)) :
                print(f"{year}_{category}_{dep}")        
                usecols='B:K'
                skiprows=6
                names=names_an_1
                nrows=25
                skipfooter=0
            elif (("Anemia" in dep) and ("DIRESA" in dep)) :
                print(f"{year}_{category}_{dep}")        
                usecols='B:K'
                skiprows=6
                names=names_an_1
                nrows=29
                skipfooter=0
            elif (("Anemia" in dep) and ("DISTRITO" in dep)) :
                print(f"{year}_{category}_{dep}")        
                usecols='B:N'
                skiprows=6
                names=names_an_2
                nrows=None
                skipfooter=3
                
            df=pd.read_excel(f"./data/{year}/{category}/{category}_{year}_{month_ranges}.xlsx",
                             sheet_name=dep,
                             usecols=usecols,
                             skiprows=skiprows,
                             nrows=nrows,
                             skipfooter=skipfooter,
                             engine='openpyxl',
                             header=None,
                             names=names)
        elif category=="VRAEM_children":    
            
            if (("EN" in dep) and ("DISTRITO" in dep)):
                print(f"{year}_{category}_{dep}")        
                skiprows=7
                usecols="B:X"
                names=names_en_2
                nrows=None
                skipfooter=6
            elif (("Anemia" in dep) and ("DISTRITO" in dep)) :
                print(f"{year}_{category}_{dep}")        
                usecols='B:N'
                skiprows=6
                names=names_an_2
                nrows=None
                skipfooter=4
                
            df=pd.read_excel(f"./data/{year}/{category}/{category}_{year}_{month_ranges}.xlsx",
                             sheet_name=dep,
                             usecols=usecols,
                             skiprows=skiprows,
                             nrows=nrows,
                             skipfooter=skipfooter,
                             engine='openpyxl',
                             header=None,
                             names=names)        
        elif category=="pregnant_women":
            
            if (("IMC_PG-CLAP" in dep)and("DEP" in dep)):    
                print(f"{year}_{category}_{dep}")        
                skiprows=7
                usecols="B:N"
                names=names_imc_clap_1
                nrows=25
                skipfooter=0
                
            elif (("IMC_PG-CLAP" in dep)and("DIRESA" in dep)):    
                print(f"{year}_{category}_{dep}")        
                skiprows=7
                usecols="B:N"
                names=names_imc_clap_1
                nrows=34
                skipfooter=0  
                
            elif (("IMC_PG-CLAP" in dep) and ("DISTRITO" in dep)):
                print(f"{year}_{category}_{dep}")        
                skiprows=7
                usecols="B:Q"
                names=names_imc_clap_2
                nrows=None
                skipfooter=7
            
            elif (("Anemia" in dep) and ("DEP" in dep)) :
                print(f"{year}_{category}_{dep}")        
                usecols='B:K'
                skiprows=6
                names=names_an_1
                nrows=25
                skipfooter=0
            elif (("Anemia" in dep) and ("DIRESA" in dep)) :
                print(f"{year}_{category}_{dep}")        
                usecols='B:K'
                skiprows=6
                names=names_an_1
                nrows=34
                skipfooter=0                
            elif (("Anemia" in dep) and ("DISTRITO" in dep)) :
                print(f"{year}_{category}_{dep}")        
                usecols='B:N'
                skiprows=6
                names=names_an_2
                nrows=None
                skipfooter=6
                
            df=pd.read_excel(f"./data/{year}/{category}/{category}_{year}_{month_ranges}.xlsx",
                             sheet_name=dep,
                             usecols=usecols,
                             skiprows=skiprows,
                             nrows=nrows,
                             skipfooter=skipfooter,
                             engine='openpyxl',
                             header=None,
                             names=names)                    

    return df

In [54]:
from openpyxl import load_workbook
year="2022"
category="children"
month_ranges="01_03"

try:
    wb = load_workbook(filename = f"./data/{year}/{category}/{category}_{year}_{month_ranges}.xlsx")

    sheets= wb.sheetnames[1:]

    for sheet in sheets:
        dep=sheet
        print(dep)
        df=make_df(year=year,category=category,month_ranges=month_ranges,dep=dep)
        df = df.replace(['*','(SD)'], 0)
        display(df)
except FileNotFoundError:
    print("no such file or directory")

EN 0-35m x DEP
2022_children_EN 0-35m x DEP

,Department,ITE_DC:Total,ITE_DC:Cases,ITE_DC:Rate,ITE_RDC:Total,ITE_RDC:Cases,ITE_RDC:Rate,IPE_DG:Total,IPE_DG:Cases,IPE_DG:Rate,IPT_DA:Total,IPT_DA:Cases,IPT_DA:Rate,IPT:Total,IPT_RDA:Cases,IPT_RDA:Rate,IPT_SP:Cases,IPT_SP:Rate,IPT_O:Cases,IPT_O:Rate
0,AMAZONAS,20623,4157,20.157106,16466,6514,39.560306,20623,847,4.107065,20623,353,1.711681,18533,1257,6.782496,1347,6.531542,390,1.891092
1,ANCASH,23161,4035,17.421528,19126,7394,38.659417,23161,926,3.998100,23161,308,1.329822,21006,1386,6.598115,1547,6.679332,300,1.295281
2,APURIMAC,9600,1475,15.364583,8125,3369,41.464615,9600,419,4.364583,9600,110,1.145833,9022,713,7.902904,389,4.052083,79,0.822917
3,AREQUIPA,20229,1370,6.772455,18859,4252,22.546264,20229,427,2.110831,20229,250,1.235850,18301,1120,6.119884,1350,6.673587,328,1.621435
4,AYACUCHO,21160,3329,15.732514,17831,7386,41.422242,21160,831,3.927221,21160,247,1.167297,19676,1378,7.003456,1042,4.924386,195,0.921550
5,CAJAMARCA,54329,11341,20.874671,42988,19164,44.579883,54329,2384,4.388080,54329,748,1.376797,49777,3347,6.723989,3118,5.739108,686,1.262677
6,CALLAO,8629,587,6.802642,8042,1713,21.300671,8629,180,2.085989,8629,139,1.610847,7418,403,5.432731,848,9.827326,224,2.595898
7,CUSCO,30975,3771,12.174334,27204,9600,35.288928,30975,1127,3.638418,30975,458,1.478612,29141,2303,7.902955,1153,3.722357,223,0.719935
8,HUANCAVELICA,11276,2433,21.576800,8843,4272,48.309397,11276,488,4.327776,11276,149,1.321391,10438,680,6.514658,573,5.081589,116,1.028734
9,HUANUCO,23459,3747,15.972548,19712,7204,36.546266,23459,887,3.781065,23459,309,1.317192,21508,1463,6.802120,1361,5.801611,281,1.197835
10,ICA,17744,1089,6.137286,16655,3542,21.266887,17744,338,1.904869,17744,209,1.177863,15707,1016,6.468454,1474,8.307033,354,1.995041
11,JUNIN,18728,2979,15.906664,15749,5550,35.240333,18728,886,4.730884,18728,337,1.799445,17268,1460,8.454946,918,4.901751,205,1.094618
12,LA LIBERTAD,28104,4346,15.463991,23758,7618,32.064989,28104,959,3.412326,28104,450,1.601196,24765,1652,6.670705,2279,8.109166,610,2.170510
13,LAMBAYEQUE,15883,2212,13.926840,13671,3818,27.927730,15883,563,3.544670,15883,365,2.298055,13697,1035,7.556399,1370,8.625575,451,2.839514
14,LIMA,88204,6686,7.580155,81518,17260,21.173238,88204,2026,2.296948,88204,1985,2.250465,75849,5497,7.247294,7873,8.925899,2497,2.830937
15,LORETO,37351,7647,20.473347,29704,12318,41.469162,37351,2914,7.801665,37351,1230,3.293085,33914,3783,11.154685,1711,4.580868,496,1.327943
16,MADRE DE DIOS,6331,541,8.545254,5790,1384,23.903282,6331,212,3.348602,6331,150,2.369294,5818,549,9.436232,282,4.454273,81,1.279419
17,MOQUEGUA,2742,106,3.865791,2636,442,16.767830,2742,33,1.203501,2742,33,1.203501,2375,118,4.968421,261,9.518600,73,2.662290
18,PASCO,8031,1326,16.511020,6705,2531,37.747949,8031,411,5.117669,8031,189,2.353381,7360,648,8.804348,394,4.905989,88,1.095754
19,PIURA,56142,8710,15.514232,47432,16261,34.282763,56142,2263,4.030850,56142,963,1.715293,50275,3895,7.747389,3868,6.889673,1036,1.845321
20,PUNO,23632,2818,11.924509,20814,7288,35.014894,23632,702,2.970548,23632,321,1.358328,21804,1274,5.842965,1284,5.433311,223,0.943636
21,SAN MARTIN,30496,3550,11.640871,26946,8192,30.401544,30496,1240,4.066107,30496,694,2.275708,27856,2838,10.188110,1532,5.023610,414,1.357555
22,TACNA,3681,134,3.640315,3547,488,13.758105,3681,26,0.706330,3681,39,1.059495,3129,159,5.081496,386,10.486281,127,3.450149
23,TUMBES,5963,474,7.949019,5489,1219,22.208052,5963,170,2.850914,5963,120,2.012410,5317,436,8.200113,420,7.043435,106,1.777629
24,UCAYALI,18577,2982,16.052107,15595,5303,34.004489,18577,1067,5.743662,18577,469,2.524627,16975,1699,10.008837,881,4.742423,252,1.356516

EN 0-35m x DIRESA
2022_children_EN 0-35m x DIRESA

,Department,ITE_DC:Total,ITE_DC:Cases,ITE_DC:Rate,ITE_RDC:Total,ITE_RDC:Cases,ITE_RDC:Rate,IPE_DG:Total,IPE_DG:Cases,IPE_DG:Rate,IPT_DA:Total,IPT_DA:Cases,IPT_DA:Rate,IPT:Total,IPT_RDA:Cases,IPT_RDA:Rate,IPT_SP:Cases,IPT_SP:Rate,IPT_O:Cases,IPT_O:Rate
0,AMAZONAS,20623,4157,20.157106,16466,6514,39.560306,20623,847,4.107065,20623,353,1.711681,18533,1257,6.782496,1347,6.531542,390,1.891092
1,ANCASH,23161,4035,17.421528,19126,7394,38.659417,23161,926,3.998100,23161,308,1.329822,21006,1386,6.598115,1547,6.679332,300,1.295281
2,APURIMAC,9600,1475,15.364583,8125,3369,41.464615,9600,419,4.364583,9600,110,1.145833,9022,713,7.902904,389,4.052083,79,0.822917
3,AREQUIPA,20229,1370,6.772455,18859,4252,22.546264,20229,427,2.110831,20229,250,1.235850,18301,1120,6.119884,1350,6.673587,328,1.621435
4,AYACUCHO,21160,3329,15.732514,17831,7386,41.422242,21160,831,3.927221,21160,247,1.167297,19676,1378,7.003456,1042,4.924386,195,0.921550
5,CAJAMARCA,54329,11341,20.874671,42988,19164,44.579883,54329,2384,4.388080,54329,748,1.376797,49777,3347,6.723989,3118,5.739108,686,1.262677
6,CALLAO,8629,587,6.802642,8042,1713,21.300671,8629,180,2.085989,8629,139,1.610847,7418,403,5.432731,848,9.827326,224,2.595898
7,CUSCO,30975,3771,12.174334,27204,9600,35.288928,30975,1127,3.638418,30975,458,1.478612,29141,2303,7.902955,1153,3.722357,223,0.719935
8,HUANCAVELICA,11276,2433,21.576800,8843,4272,48.309397,11276,488,4.327776,11276,149,1.321391,10438,680,6.514658,573,5.081589,116,1.028734
9,HUANUCO,23459,3747,15.972548,19712,7204,36.546266,23459,887,3.781065,23459,309,1.317192,21508,1463,6.802120,1361,5.801611,281,1.197835
10,ICA,17744,1089,6.137286,16655,3542,21.266887,17744,338,1.904869,17744,209,1.177863,15707,1016,6.468454,1474,8.307033,354,1.995041
11,JUNIN,18728,2979,15.906664,15749,5550,35.240333,18728,886,4.730884,18728,337,1.799445,17268,1460,8.454946,918,4.901751,205,1.094618
12,LA LIBERTAD,28104,4346,15.463991,23758,7618,32.064989,28104,959,3.412326,28104,450,1.601196,24765,1652,6.670705,2279,8.109166,610,2.170510
13,LAMBAYEQUE,15883,2212,13.926840,13671,3818,27.927730,15883,563,3.544670,15883,365,2.298055,13697,1035,7.556399,1370,8.625575,451,2.839514
14,LIMA DIRIS CENTRO,14706,955,6.493948,13751,2840,20.653043,14706,362,2.461580,14706,341,2.318781,12772,1002,7.845287,1245,8.465932,348,2.366381
15,LIMA DIRIS ESTE,13748,959,6.975560,12789,2524,19.735710,13748,277,2.014839,13748,362,2.633110,11755,846,7.196937,1237,8.997672,394,2.865871
16,LIMA DIRIS NORTE,25470,1890,7.420495,23580,4471,18.960984,25470,692,2.716922,25470,742,2.913231,21900,1883,8.598174,2126,8.347075,702,2.756184
17,LIMA DIRIS SUR,13703,1056,7.706342,12647,2591,20.487072,13703,282,2.057944,13703,273,1.992264,11773,831,7.058524,1227,8.954244,430,3.137999
18,LIMA PROVINCIAS,20577,1826,8.873986,18751,4834,25.779958,20577,413,2.007095,20577,267,1.297565,17649,935,5.297751,2038,9.904262,623,3.027652
19,LORETO,37351,7647,20.473347,29704,12318,41.469162,37351,2914,7.801665,37351,1230,3.293085,33914,3783,11.154685,1711,4.580868,496,1.327943
20,MADRE DE DIOS,6331,541,8.545254,5790,1384,23.903282,6331,212,3.348602,6331,150,2.369294,5818,549,9.436232,282,4.454273,81,1.279419
21,MOQUEGUA,2742,106,3.865791,2636,442,16.767830,2742,33,1.203501,2742,33,1.203501,2375,118,4.968421,261,9.518600,73,2.662290
22,PASCO,8031,1326,16.511020,6705,2531,37.747949,8031,411,5.117669,8031,189,2.353381,7360,648,8.804348,394,4.905989,88,1.095754
23,PIURA,56142,8710,15.514232,47432,16261,34.282763,56142,2263,4.030850,56142,963,1.715293,50275,3895,7.747389,3868,6.889673,1036,1.845321
24,PUNO,23632,2818,11.924509,20814,7288,35.014894,23632,702,2.970548,23632,321,1.358328,21804,1274,5.842965,1284,5.433311,223,0.943636
25,SAN MARTIN,30496,3550,11.640871,26946,8192,30.401544,30496,1240,4.066107,30496,694,2.275708,27856,2838,10.188110,1532,5.023610,414,1.357555
26,TACNA,3681,134,3.640315,3547,488,13.758105,3681,26,0.706330,3681,39,1.059495,3129,159,5.081496,386,10.486281,127,3.450149
27,TUMBES,5963,474,7.949019,5489,1219,22.208052,5963,170,2.850914,5963,120,2.012410,5317,436,8.200113,420,7.043435,106,1.777629
28,UCAYALI,18577,2982,16.052107,15595,5303,34.004489,18577,1067,5.743662,18577,469,2.524627,16975,1699,10.008837,881,4.742423,252,1.356516

EN 0-35m x DISTRITO
2022_children_EN 0-35m x DISTRITO

,Department,Province,District,Ubigeous,ITE_DC:Total,ITE_DC:Cases,ITE_DC:Rate,ITE_RDC:Total,ITE_RDC:Cases,ITE_RDC:Rate,...,IPT_DA:Total,IPT_DA:Cases,IPT_DA:Rate,IPT_RDA:Total,IPT_RDA:Cases,IPT_RDA:Rate,IPT_SP:Cases,IPT_SP:Rate,IPT_O:Cases,IPT_O:Rate
0,AMAZONAS,BAGUA,ARAMANGO,10202,482,68,14.107884,414,151,36.473430,...,482,8,1.659751,436,32,7.339450,30,6.224066,8,1.659751
1,NaN,NaN,BAGUA,10201,962,95,9.875260,867,282,32.525952,...,962,15,1.559252,862,60,6.960557,64,6.652807,21,2.182952
2,NaN,NaN,COPALLIN,10203,160,17,10.625000,143,43,30.069930,...,160,8,5.000000,149,13,8.724832,3,1.875000,0,0.000000
3,NaN,NaN,EL PARCO,10204,50,4,8.000000,46,17,36.956522,...,50,0,0.000000,45,3,6.666667,5,10.000000,0,0.000000
4,NaN,NaN,IMAZA,10205,2905,949,32.667814,1956,990,50.613497,...,2905,78,2.685026,2595,200,7.707129,177,6.092943,55,1.893287
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1770,NaN,NaN,CURIMANA,250303,504,70,13.888889,434,149,34.331797,...,504,5,0.992063,451,36,7.982262,33,6.547619,15,2.976190
1771,NaN,NaN,IRAZOLA,250302,426,63,14.788732,363,97,26.721763,...,426,12,2.816901,379,32,8.443272,25,5.868545,10,2.347418
1772,NaN,NaN,NESHUYA,250304,389,50,12.853470,339,92,27.138643,...,389,12,3.084833,354,38,10.734463,16,4.113111,7,1.799486
1773,NaN,NaN,PADRE ABAD,250301,1102,120,10.889292,982,270,27.494908,...,1102,20,1.814882,1014,120,11.834320,53,4.809437,15,1.361162
1774,NaN,PURUS,PURUS,250401,231,66,28.571429,165,85,51.515152,...,231,3,1.298701,214,10,4.672897,13,5.627706,1,0.432900

EN 0-59m x DEP
2022_children_EN 0-59m x DEP

,Department,ITE_DC:Total,ITE_DC:Cases,ITE_DC:Rate,ITE_RDC:Total,ITE_RDC:Cases,ITE_RDC:Rate,IPE_DG:Total,IPE_DG:Cases,IPE_DG:Rate,IPT_DA:Total,IPT_DA:Cases,IPT_DA:Rate,IPT:Total,IPT_RDA:Cases,IPT_RDA:Rate,IPT_SP:Cases,IPT_SP:Rate,IPT_O:Cases,IPT_O:Rate
0,AMAZONAS,30096,6520,21.664009,23576,10092,42.806244,30096,1280,4.253057,30096,485,1.611510,27312,1756,6.429408,1770,5.881180,529,1.757709
1,ANCASH,32303,6225,19.270656,26078,10962,42.035432,32303,1334,4.129647,32303,411,1.272328,29482,1860,6.308934,1962,6.073739,448,1.386868
2,APURIMAC,13191,2119,16.063983,11072,4854,43.840318,13191,539,4.086119,13191,150,1.137139,12442,913,7.338049,495,3.752559,104,0.788416
3,AREQUIPA,25416,1773,6.975921,23643,5568,23.550311,25416,501,1.971199,25416,314,1.235442,22846,1312,5.742800,1746,6.869688,510,2.006610
4,AYACUCHO,28819,4829,16.756307,23990,10621,44.272614,28819,1084,3.761407,28819,321,1.113849,26974,1773,6.572996,1274,4.420695,250,0.867483
5,CAJAMARCA,79409,17237,21.706608,62172,29350,47.207746,79409,3620,4.558677,79409,1069,1.346195,73337,4828,6.583307,4037,5.083807,966,1.216487
6,CALLAO,9933,693,6.976744,9240,2008,21.731602,9933,218,2.194705,9933,174,1.751737,8513,493,5.791143,952,9.584214,294,2.959831
7,CUSCO,40560,5379,13.261834,35181,13319,37.858503,40560,1445,3.562623,40560,561,1.383136,38178,2822,7.391692,1509,3.720414,312,0.769231
8,HUANCAVELICA,16862,3977,23.585577,12885,6741,52.316647,16862,748,4.436010,16862,242,1.435180,15726,939,5.971003,734,4.352983,160,0.948879
9,HUANUCO,33743,5865,17.381383,27878,11213,40.221680,33743,1239,3.671873,33743,407,1.206176,31096,1957,6.293414,1822,5.399638,418,1.238775
10,ICA,20684,1268,6.130342,19416,4213,21.698599,20684,411,1.987043,20684,281,1.358538,18227,1261,6.918308,1723,8.330110,453,2.190099
11,JUNIN,23830,4063,17.049937,19767,7582,38.356857,23830,1108,4.649601,23830,394,1.653378,22072,1759,7.969373,1117,4.687369,247,1.036509
12,LA LIBERTAD,36679,6387,17.413234,30292,10684,35.270038,36679,1358,3.702391,36679,577,1.573107,32544,2147,6.597222,2763,7.532921,795,2.167453
13,LAMBAYEQUE,18505,2715,14.671710,15790,4631,29.328689,18505,655,3.539584,18505,415,2.242637,15969,1165,7.295385,1570,8.484193,551,2.977574
14,LIMA,106465,8174,7.677641,98291,21379,21.750720,106465,2525,2.371671,106465,2645,2.484385,91246,6950,7.616772,9319,8.753111,3255,3.057343
15,LORETO,48580,10222,21.041581,38358,16866,43.969967,48580,3698,7.612186,48580,1566,3.223549,44341,4763,10.741751,2009,4.135447,664,1.366818
16,MADRE DE DIOS,7818,700,8.953697,7118,1786,25.091318,7818,269,3.440778,7818,214,2.737273,7118,674,9.468952,365,4.668713,121,1.547710
17,MOQUEGUA,3490,147,4.212034,3343,597,17.858211,3490,43,1.232092,3490,44,1.260745,2985,148,4.958124,358,10.257880,103,2.951289
18,PASCO,11148,1912,17.151058,9236,3685,39.898224,11148,537,4.817008,11148,235,2.108001,10253,875,8.534088,526,4.718335,134,1.202009
19,PIURA,74622,12210,16.362467,62412,22359,35.824841,74622,3061,4.102007,74622,1242,1.664389,66883,5039,7.534052,4976,6.668275,1521,2.038273
20,PUNO,32630,3887,11.912351,28743,10582,36.815920,32630,861,2.638676,32630,420,1.287159,30129,1613,5.353646,1770,5.424456,311,0.953111
21,SAN MARTIN,41967,5007,11.930803,36960,11925,32.264610,41967,1681,4.005528,41967,963,2.294660,38450,3853,10.020806,1945,4.634594,609,1.451140
22,TACNA,5231,183,3.498375,5048,741,14.679081,5231,32,0.611738,5231,54,1.032307,4378,210,4.796711,570,10.896578,229,4.377748
23,TUMBES,6874,534,7.768403,6340,1419,22.381703,6874,191,2.778586,6874,150,2.182136,6091,510,8.373009,487,7.084667,146,2.123945
24,UCAYALI,22319,3720,16.667413,18599,6613,35.555675,22319,1276,5.717102,22319,575,2.576280,20423,1998,9.783088,1010,4.525292,311,1.393432

EN 0-59m x DIRESA
2022_children_EN 0-59m x DIRESA

,Department,ITE_DC:Total,ITE_DC:Cases,ITE_DC:Rate,ITE_RDC:Total,ITE_RDC:Cases,ITE_RDC:Rate,IPE_DG:Total,IPE_DG:Cases,IPE_DG:Rate,IPT_DA:Total,IPT_DA:Cases,IPT_DA:Rate,IPT:Total,IPT_RDA:Cases,IPT_RDA:Rate,IPT_SP:Cases,IPT_SP:Rate,IPT_O:Cases,IPT_O:Rate
0,AMAZONAS,30096,6520,21.664009,23576,10092,42.806244,30096,1280,4.253057,30096,485,1.611510,27312,1756,6.429408,1770,5.881180,529,1.757709
1,ANCASH,32303,6225,19.270656,26078,10962,42.035432,32303,1334,4.129647,32303,411,1.272328,29482,1860,6.308934,1962,6.073739,448,1.386868
2,APURIMAC,13191,2119,16.063983,11072,4854,43.840318,13191,539,4.086119,13191,150,1.137139,12442,913,7.338049,495,3.752559,104,0.788416
3,AREQUIPA,25416,1773,6.975921,23643,5568,23.550311,25416,501,1.971199,25416,314,1.235442,22846,1312,5.742800,1746,6.869688,510,2.006610
4,AYACUCHO,28819,4829,16.756307,23990,10621,44.272614,28819,1084,3.761407,28819,321,1.113849,26974,1773,6.572996,1274,4.420695,250,0.867483
5,CAJAMARCA,79409,17237,21.706608,62172,29350,47.207746,79409,3620,4.558677,79409,1069,1.346195,73337,4828,6.583307,4037,5.083807,966,1.216487
6,CALLAO,9933,693,6.976744,9240,2008,21.731602,9933,218,2.194705,9933,174,1.751737,8513,493,5.791143,952,9.584214,294,2.959831
7,CUSCO,40560,5379,13.261834,35181,13319,37.858503,40560,1445,3.562623,40560,561,1.383136,38178,2822,7.391692,1509,3.720414,312,0.769231
8,HUANCAVELICA,16862,3977,23.585577,12885,6741,52.316647,16862,748,4.436010,16862,242,1.435180,15726,939,5.971003,734,4.352983,160,0.948879
9,HUANUCO,33743,5865,17.381383,27878,11213,40.221680,33743,1239,3.671873,33743,407,1.206176,31096,1957,6.293414,1822,5.399638,418,1.238775
10,ICA,20684,1268,6.130342,19416,4213,21.698599,20684,411,1.987043,20684,281,1.358538,18227,1261,6.918308,1723,8.330110,453,2.190099
11,JUNIN,23830,4063,17.049937,19767,7582,38.356857,23830,1108,4.649601,23830,394,1.653378,22072,1759,7.969373,1117,4.687369,247,1.036509
12,LA LIBERTAD,36679,6387,17.413234,30292,10684,35.270038,36679,1358,3.702391,36679,577,1.573107,32544,2147,6.597222,2763,7.532921,795,2.167453
13,LAMBAYEQUE,18505,2715,14.671710,15790,4631,29.328689,18505,655,3.539584,18505,415,2.242637,15969,1165,7.295385,1570,8.484193,551,2.977574
14,LIMA DIRIS CENTRO,17668,1138,6.441023,16530,3456,20.907441,17668,426,2.411139,17668,431,2.439439,15296,1225,8.008630,1473,8.337107,468,2.648857
15,LIMA DIRIS ESTE,16840,1182,7.019002,15658,3146,20.091966,16840,372,2.209026,16840,491,2.915677,14383,1192,8.287562,1452,8.622328,514,3.052257
16,LIMA DIRIS NORTE,29611,2195,7.412786,27416,5264,19.200467,29611,824,2.782750,29611,984,3.323089,25281,2284,9.034453,2458,8.300969,888,2.998886
17,LIMA DIRIS SUR,15953,1264,7.923275,14689,3072,20.913609,15953,355,2.225287,15953,368,2.306776,13641,1029,7.543435,1407,8.819658,537,3.366138
18,LIMA PROVINCIAS,26393,2395,9.074376,23998,6441,26.839737,26393,548,2.076308,26393,371,1.405676,22645,1220,5.387503,2529,9.582086,848,3.212973
19,LORETO,48580,10222,21.041581,38358,16866,43.969967,48580,3698,7.612186,48580,1566,3.223549,44341,4763,10.741751,2009,4.135447,664,1.366818
20,MADRE DE DIOS,7818,700,8.953697,7118,1786,25.091318,7818,269,3.440778,7818,214,2.737273,7118,674,9.468952,365,4.668713,121,1.547710
21,MOQUEGUA,3490,147,4.212034,3343,597,17.858211,3490,43,1.232092,3490,44,1.260745,2985,148,4.958124,358,10.257880,103,2.951289
22,PASCO,11148,1912,17.151058,9236,3685,39.898224,11148,537,4.817008,11148,235,2.108001,10253,875,8.534088,526,4.718335,134,1.202009
23,PIURA,74622,12210,16.362467,62412,22359,35.824841,74622,3061,4.102007,74622,1242,1.664389,66883,5039,7.534052,4976,6.668275,1521,2.038273
24,PUNO,32630,3887,11.912351,28743,10582,36.815920,32630,861,2.638676,32630,420,1.287159,30129,1613,5.353646,1770,5.424456,311,0.953111
25,SAN MARTIN,41967,5007,11.930803,36960,11925,32.264610,41967,1681,4.005528,41967,963,2.294660,38450,3853,10.020806,1945,4.634594,609,1.451140
26,TACNA,5231,183,3.498375,5048,741,14.679081,5231,32,0.611738,5231,54,1.032307,4378,210,4.796711,570,10.896578,229,4.377748
27,TUMBES,6874,534,7.768403,6340,1419,22.381703,6874,191,2.778586,6874,150,2.182136,6091,510,8.373009,487,7.084667,146,2.123945
28,UCAYALI,22319,3720,16.667413,18599,6613,35.555675,22319,1276,5.717102,22319,575,2.576280,20423,1998,9.783088,1010,4.525292,311,1.393432

EN 0-59m x DISTRITO
2022_children_EN 0-59m x DISTRITO

,Department,Province,District,Ubigeous,ITE_DC:Total,ITE_DC:Cases,ITE_DC:Rate,ITE_RDC:Total,ITE_RDC:Cases,ITE_RDC:Rate,...,IPT_DA:Total,IPT_DA:Cases,IPT_DA:Rate,IPT_RDA:Total,IPT_RDA:Cases,IPT_RDA:Rate,IPT_SP:Cases,IPT_SP:Rate,IPT_O:Cases,IPT_O:Rate
0,AMAZONAS,BAGUA,ARAMANGO,10202,805,139,17.267081,666,266,39.939940,...,805,13,1.614907,737,50,6.784261,41,5.093168,14,1.739130
1,NaN,NaN,BAGUA,10201,1318,128,9.711684,1190,376,31.596639,...,1318,23,1.745068,1179,79,6.700594,83,6.297420,33,2.503794
2,NaN,NaN,COPALLIN,10203,248,26,10.483871,222,80,36.036036,...,248,9,3.629032,233,23,9.871245,6,2.419355,0,0.000000
3,NaN,NaN,EL PARCO,10204,77,9,11.688312,68,29,42.647059,...,77,0,0.000000,71,5,7.042254,6,7.792208,0,0.000000
4,NaN,NaN,IMAZA,10205,4214,1548,36.734694,2666,1479,55.476369,...,4214,91,2.159468,3805,253,6.649146,236,5.600380,82,1.945895
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1772,NaN,NaN,CURIMANA,250303,673,89,13.224368,584,212,36.301370,...,673,10,1.485884,609,51,8.374384,37,5.497771,17,2.526003
1773,NaN,NaN,IRAZOLA,250302,505,75,14.851485,430,125,29.069767,...,505,15,2.970297,447,38,8.501119,31,6.138614,12,2.376238
1774,NaN,NaN,NESHUYA,250304,475,65,13.684211,410,127,30.975610,...,475,15,3.157895,433,48,11.085450,18,3.789474,9,1.894737
1775,NaN,NaN,PADRE ABAD,250301,1277,151,11.824589,1126,336,29.840142,...,1277,23,1.801096,1176,128,10.884354,61,4.776821,17,1.331245
1776,NaN,PURUS,PURUS,250401,313,103,32.907348,210,113,53.809524,...,313,5,1.597444,287,14,4.878049,19,6.070288,2,0.638978

Anemia 6-35m x DEP
2022_children_Anemia 6-35m x DEP

,Department,Total,AT:Cases,AT:Rate,AL:Cases,AL:Rate,AM:Cases,AM:Rate,AS:Cases,AS:Rate
0,AMAZONAS,4116,946,22.983479,685,16.642371,260,6.316812,1,0.024295
1,ANCASH,9073,4083,45.001653,2262,24.931114,1782,19.640692,39,0.429847
2,APURIMAC,4048,1254,30.978261,831,20.528656,413,10.202569,10,0.247036
3,AREQUIPA,6645,1845,27.765237,1213,18.254327,621,9.345372,11,0.165538
4,AYACUCHO,8442,2585,30.620706,1624,19.237148,951,11.265103,10,0.118455
5,CAJAMARCA,11768,2908,24.711081,2078,17.658056,824,7.002039,6,0.050986
6,CALLAO,5548,1291,23.269647,872,15.717376,414,7.462149,5,0.090123
7,CUSCO,9635,3805,39.491437,2180,22.625843,1556,16.149455,69,0.716139
8,HUANCAVELICA,3116,1407,45.154044,732,23.491656,643,20.635430,32,1.026958
9,HUANUCO,5954,1307,21.951629,898,15.082298,400,6.718173,9,0.151159
10,ICA,5530,1482,26.799277,1089,19.692586,392,7.088608,1,0.018083
11,JUNIN,9673,3353,34.663496,2354,24.335780,982,10.151969,17,0.175747
12,LA LIBERTAD,11679,3913,33.504581,2177,18.640295,1695,14.513229,41,0.351057
13,LAMBAYEQUE,6292,2236,35.537190,1361,21.630642,858,13.636364,17,0.270184
14,LIMA,42517,11876,27.932356,8566,20.147235,3261,7.669873,49,0.115248
15,LORETO,9188,3302,35.938180,2042,22.224641,1251,13.615586,9,0.097954
16,MADRE DE DIOS,1680,548,32.619048,332,19.761905,215,12.797619,1,0.059524
17,MOQUEGUA,773,200,25.873221,133,17.205692,67,8.667529,0,0.000000
18,PASCO,2210,905,40.950226,530,23.981900,355,16.063348,20,0.904977
19,PIURA,15825,3307,20.897314,2379,15.033175,923,5.832543,5,0.031596
20,PUNO,7092,2950,41.596165,1642,23.152848,1261,17.780598,47,0.662719
21,SAN MARTIN,7179,1698,23.652319,1358,18.916284,339,4.722106,1,0.013930
22,TACNA,1520,442,29.078947,328,21.578947,112,7.368421,2,0.131579
23,TUMBES,1891,413,21.840296,277,14.648334,136,7.191962,0,0.000000
24,UCAYALI,5798,2069,35.684719,1342,23.145912,725,12.504312,2,0.034495

Anemia 6-35m x DIRESA
2022_children_Anemia 6-35m x DIRESA

,Department,Total,AT:Cases,AT:Rate,AL:Cases,AL:Rate,AM:Cases,AM:Rate,AS:Cases,AS:Rate
0,AMAZONAS,4116,946,22.983479,685,16.642371,260,6.316812,1,0.024295
1,ANCASH,9073,4083,45.001653,2262,24.931114,1782,19.640692,39,0.429847
2,APURIMAC,4048,1254,30.978261,831,20.528656,413,10.202569,10,0.247036
3,AREQUIPA,6645,1845,27.765237,1213,18.254327,621,9.345372,11,0.165538
4,AYACUCHO,8442,2585,30.620706,1624,19.237148,951,11.265103,10,0.118455
5,CAJAMARCA,11768,2908,24.711081,2078,17.658056,824,7.002039,6,0.050986
6,CALLAO,5548,1291,23.269647,872,15.717376,414,7.462149,5,0.090123
7,CUSCO,9635,3805,39.491437,2180,22.625843,1556,16.149455,69,0.716139
8,HUANCAVELICA,3116,1407,45.154044,732,23.491656,643,20.635430,32,1.026958
9,HUANUCO,5954,1307,21.951629,898,15.082298,400,6.718173,9,0.151159
10,ICA,5530,1482,26.799277,1089,19.692586,392,7.088608,1,0.018083
11,JUNIN,9673,3353,34.663496,2354,24.335780,982,10.151969,17,0.175747
12,LA LIBERTAD,11679,3913,33.504581,2177,18.640295,1695,14.513229,41,0.351057
13,LAMBAYEQUE,6292,2236,35.537190,1361,21.630642,858,13.636364,17,0.270184
14,LIMA DIRIS CENTRO,11241,2486,22.115470,1894,16.849035,590,5.248643,2,0.017792
15,LIMA DIRIS ESTE,5616,1983,35.309829,1384,24.643875,594,10.576923,5,0.089031
16,LIMA DIRIS NORTE,10017,3176,31.706100,2405,24.009184,770,7.686932,1,0.009983
17,LIMA DIRIS SUR,8814,2642,29.975040,1900,21.556614,735,8.339006,7,0.079419
18,LIMA PROVINCIAS,6829,1589,23.268414,983,14.394494,572,8.376043,34,0.497877
19,LORETO,9188,3302,35.938180,2042,22.224641,1251,13.615586,9,0.097954
20,MADRE DE DIOS,1680,548,32.619048,332,19.761905,215,12.797619,1,0.059524
21,MOQUEGUA,773,200,25.873221,133,17.205692,67,8.667529,0,0.000000
22,PASCO,2210,905,40.950226,530,23.981900,355,16.063348,20,0.904977
23,PIURA,15825,3307,20.897314,2379,15.033175,923,5.832543,5,0.031596
24,PUNO,7092,2950,41.596165,1642,23.152848,1261,17.780598,47,0.662719
25,SAN MARTIN,7179,1698,23.652319,1358,18.916284,339,4.722106,1,0.013930
26,TACNA,1520,442,29.078947,328,21.578947,112,7.368421,2,0.131579
27,TUMBES,1891,413,21.840296,277,14.648334,136,7.191962,0,0.000000
28,UCAYALI,5798,2069,35.684719,1342,23.145912,725,12.504312,2,0.034495

Anemia 6-35m x DISTRITO
2022_children_Anemia 6-35m x DISTRITO

,Department,Province,District,Ubigeous,Total,AT:Cases,AT:Rate,AL:Cases,AL:Rate,AM:Cases,AM:Rate,AS:Cases,AS:Rate
0,AMAZONAS,BAGUA,ARAMANGO,10202,93,9,9.677419,9,9.677419,0,0.000000,0,0.000000
1,NaN,NaN,BAGUA,10201,218,53,24.311927,32,14.678899,21,9.633028,0,0.000000
2,NaN,NaN,COPALLIN,10203,33,2,6.060606,2,6.060606,0,0.000000,0,0.000000
3,NaN,NaN,EL PARCO,10204,11,0,0.000000,0,0.000000,0,0.000000,0,0.000000
4,NaN,NaN,IMAZA,10205,567,177,31.216931,112,19.753086,65,11.463845,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1805,NaN,NaN,CURIMANA,250303,116,58,50.000000,34,29.310345,24,20.689655,0,0.000000
1806,NaN,NaN,IRAZOLA,250302,213,59,27.699531,46,21.596244,13,6.103286,0,0.000000
1807,NaN,NaN,NESHUYA,250304,110,56,50.909091,41,37.272727,15,13.636364,0,0.000000
1808,NaN,NaN,PADRE ABAD,250301,290,52,17.931034,24,8.275862,28,9.655172,0,0.000000
1809,NaN,PURUS,PURUS,250401,51,24,47.058824,16,31.372549,7,13.725490,1,1.960784

Anemia 6-59m x DEP
2022_children_Anemia 6-59m x DEP

,Department,Total,AT:Cases,AT:Rate,AL:Cases,AL:Rate,AM:Cases,AM:Rate,AS:Cases,AS:Rate
0,AMAZONAS,6567,1212,18.455916,899,13.689660,312,4.751028,1,0.015228
1,ANCASH,13008,5278,40.575031,2947,22.655289,2285,17.566113,46,0.353629
2,APURIMAC,6169,1642,26.616956,1090,17.668990,541,8.769655,11,0.178311
3,AREQUIPA,8962,2117,23.621959,1417,15.811203,685,7.643383,15,0.167373
4,AYACUCHO,12598,3266,25.924750,2091,16.597873,1164,9.239562,11,0.087315
5,CAJAMARCA,19013,3794,19.954768,2781,14.626834,1005,5.285857,8,0.042076
6,CALLAO,6426,1377,21.428571,941,14.643635,431,6.707127,5,0.077809
7,CUSCO,13589,4797,35.300611,2840,20.899257,1875,13.797925,82,0.603429
8,HUANCAVELICA,5059,2032,40.166041,1083,21.407393,909,17.967978,40,0.790670
9,HUANUCO,9388,1852,19.727311,1281,13.645079,558,5.943758,13,0.138475
10,ICA,6599,1572,23.821791,1165,17.654190,406,6.152447,1,0.015154
11,JUNIN,13132,3997,30.437100,2846,21.672251,1133,8.627779,18,0.137070
12,LA LIBERTAD,15936,5022,31.513554,2845,17.852661,2128,13.353414,49,0.307480
13,LAMBAYEQUE,7685,2527,32.882238,1520,19.778790,988,12.856213,19,0.247235
14,LIMA,50363,12732,25.280464,9277,18.420269,3401,6.752973,54,0.107222
15,LORETO,12874,3951,30.689762,2540,19.729688,1401,10.882399,10,0.077676
16,MADRE DE DIOS,2072,619,29.874517,389,18.774131,229,11.052124,1,0.048263
17,MOQUEGUA,1027,225,21.908471,153,14.897760,72,7.010711,0,0.000000
18,PASCO,3415,1215,35.578331,738,21.610542,455,13.323572,22,0.644217
19,PIURA,22176,3805,17.158189,2802,12.635281,998,4.500361,5,0.022547
20,PUNO,10770,3747,34.791086,2208,20.501393,1486,13.797586,53,0.492108
21,SAN MARTIN,10636,2063,19.396390,1696,15.945844,366,3.441143,1,0.009402
22,TACNA,2233,537,24.048365,404,18.092253,131,5.866547,2,0.089566
23,TUMBES,2227,437,19.622811,299,13.426134,138,6.196677,0,0.000000
24,UCAYALI,7426,2405,32.386211,1613,21.720980,789,10.624832,3,0.040399

Anemia 6-59m x DIRESA
2022_children_Anemia 6-59m x DIRESA

,Department,Total,AT:Cases,AT:Rate,AL:Cases,AL:Rate,AM:Cases,AM:Rate,AS:Cases,AS:Rate
0,AMAZONAS,6567,1212,18.455916,899,13.689660,312,4.751028,1,0.015228
1,ANCASH,13008,5278,40.575031,2947,22.655289,2285,17.566113,46,0.353629
2,APURIMAC,6169,1642,26.616956,1090,17.668990,541,8.769655,11,0.178311
3,AREQUIPA,8962,2117,23.621959,1417,15.811203,685,7.643383,15,0.167373
4,AYACUCHO,12598,3266,25.924750,2091,16.597873,1164,9.239562,11,0.087315
5,CAJAMARCA,19013,3794,19.954768,2781,14.626834,1005,5.285857,8,0.042076
6,CALLAO,6426,1377,21.428571,941,14.643635,431,6.707127,5,0.077809
7,CUSCO,13589,4797,35.300611,2840,20.899257,1875,13.797925,82,0.603429
8,HUANCAVELICA,5059,2032,40.166041,1083,21.407393,909,17.967978,40,0.790670
9,HUANUCO,9388,1852,19.727311,1281,13.645079,558,5.943758,13,0.138475
10,ICA,6599,1572,23.821791,1165,17.654190,406,6.152447,1,0.015154
11,JUNIN,13132,3997,30.437100,2846,21.672251,1133,8.627779,18,0.137070
12,LA LIBERTAD,15936,5022,31.513554,2845,17.852661,2128,13.353414,49,0.307480
13,LAMBAYEQUE,7685,2527,32.882238,1520,19.778790,988,12.856213,19,0.247235
14,LIMA DIRIS CENTRO,13577,2640,19.444649,2029,14.944391,609,4.485527,2,0.014731
15,LIMA DIRIS ESTE,6399,2112,33.005157,1497,23.394280,610,9.532739,5,0.078137
16,LIMA DIRIS NORTE,10978,3312,30.169430,2533,23.073420,778,7.086901,1,0.009109
17,LIMA DIRIS SUR,10231,2826,27.621933,2057,20.105562,762,7.447952,7,0.068420
18,LIMA PROVINCIAS,9178,1842,20.069732,1161,12.649815,642,6.994988,39,0.424929
19,LORETO,12874,3951,30.689762,2540,19.729688,1401,10.882399,10,0.077676
20,MADRE DE DIOS,2072,619,29.874517,389,18.774131,229,11.052124,1,0.048263
21,MOQUEGUA,1027,225,21.908471,153,14.897760,72,7.010711,0,0.000000
22,PASCO,3415,1215,35.578331,738,21.610542,455,13.323572,22,0.644217
23,PIURA,22176,3805,17.158189,2802,12.635281,998,4.500361,5,0.022547
24,PUNO,10770,3747,34.791086,2208,20.501393,1486,13.797586,53,0.492108
25,SAN MARTIN,10636,2063,19.396390,1696,15.945844,366,3.441143,1,0.009402
26,TACNA,2233,537,24.048365,404,18.092253,131,5.866547,2,0.089566
27,TUMBES,2227,437,19.622811,299,13.426134,138,6.196677,0,0.000000
28,UCAYALI,7426,2405,32.386211,1613,21.720980,789,10.624832,3,0.040399

Anemia 6-59m x DISTRITO
2022_children_Anemia 6-59m x DISTRITO

,Department,Province,District,Ubigeous,Total,AT:Cases,AT:Rate,AL:Cases,AL:Rate,AM:Cases,AM:Rate,AS:Cases,AS:Rate
0,AMAZONAS,BAGUA,ARAMANGO,10202,188,10,5.319149,9,4.787234,1,0.531915,0,0.000000
1,NaN,NaN,BAGUA,10201,334,58,17.365269,36,10.778443,22,6.586826,0,0.000000
2,NaN,NaN,COPALLIN,10203,58,4,6.896552,4,6.896552,0,0.000000,0,0.000000
3,NaN,NaN,EL PARCO,10204,19,0,0.000000,0,0.000000,0,0.000000,0,0.000000
4,NaN,NaN,IMAZA,10205,887,221,24.915445,144,16.234498,77,8.680947,0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1805,NaN,NaN,CURIMANA,250303,162,64,39.506173,38,23.456790,26,16.049383,0,0.000000
1806,NaN,NaN,IRAZOLA,250302,274,72,26.277372,58,21.167883,14,5.109489,0,0.000000
1807,NaN,NaN,NESHUYA,250304,135,64,47.407407,48,35.555556,16,11.851852,0,0.000000
1808,NaN,NaN,PADRE ABAD,250301,369,58,15.718157,28,7.588076,30,8.130081,0,0.000000
1809,NaN,PURUS,PURUS,250401,77,26,33.766234,18,23.376623,7,9.090909,1,1.298701

In [1]:
from sqlalchemy import create_engine

In [40]:
sheet = wb['IMC_PG-CLAP x DEP']
dir(sheet)
print(sheet.min_column,sheet.max_column)

2 14

In [37]:
sheet.dimensions

'B2:N38'

In [39]:
sheet.min_column

2

In [ ]:
s = pd.Series([np.nan, "single_one", np.nan,
               "fill_two_more", np.nan, np.nan, np.nan,
               4.71, np.nan])